### ISSUE TITLE
Conway's Game of Life With :poop:

### ISSUE THREAD

**Issue by cdipaolo** [ncase/emoji-prototype#3]
http://ncase.me/emoji-prototype/?remote=-K4Bg6dAVErZHswOJO4T

Saw the call to action in the sidebar. In case you want to use it as an example or something!

**Comment by atenefyr** [comment]
You are way too late .-.

**Comment by ncase** [comment]
Ha, thanks @cdipaolo! Someone else beat you to the punch, but here, have 10 poopy-points anyway. :P
💩💩💩💩💩 💩💩💩💩💩
